import os

chapter_dir = os.path.join(os.getcwd(), '03_School_and_DAS', 'dissertation_chapters')
sources_dir = os.path.join(os.getcwd(), 'notebook_sources')

os.makedirs(chapter_dir, exist_ok=True)
os.makedirs(sources_dir, exist_ok=True)

ch1_content = """# BOWIE STATE UNIVERSITY
## Department of Computer Science — Doctor of Applied Science (D.A.S.) Program

---

### DISSERTATION CHAPTER 1: INTRODUCTION & FORMAL SAFETY FRAMEWORK

* **Title:** Deterministic Guardrails in Autonomous Large Language Model Pipelines via Thread-Isolated SMT Logit Transformation and Hardware-Attested Memory Enclaves
* **Candidate:** Asaad Morman
* **Degree Program:** Doctor of Applied Science (D.A.S.) in Computer Science
* **Institution:** Bowie State University
* **Hardware Provenance Signature:** `HW_KEY_0x889_BSU_DAS_2026_EDR`

---

## 1.1 Introduction & Problem Statement

The rapid integration of Large Language Models (LLMs) into defense-critical, autonomous Security Operations Centers (SOC) and Controlled Unclassified Information (CUI) environments has exposed a fundamental security vulnerability: current AI safety architectures are probabilistic. Standard guardrails rely primarily on Reinforcement Learning from Human Feedback (RLHF), system instructions, or post-hoc logit filtering. These mechanisms operate downstream of the foundational token generation probabilities, yielding a non-zero probability of security policy violation ($P_{\\text{violation}} > 0$). Under adversarial prompt injection, jailbreaking techniques, or vector inversion attacks, soft probabilistic safety boundaries consistently degrade, creating severe risks of classified data spillage and unauthenticated command execution.

Furthermore, state-of-the-art enterprise AI deployments treat software enclaves, vector retrieval databases, and power infrastructure as decoupled abstractions. When high-throughput vector retrieval systems (e.g., Retrieval-Augmented Generation) operate without hardware-attested memory guarantees or differential privacy protections, embeddings remain vulnerable to inversion attacks that reconstruct raw sensitive text. In tactical expeditionary command posts, these compute-intensive AI workloads depend on fixed commercial power grids, lacking real-time adaptation for off-grid microgrids or thermal exhaust recapture.

To bridge this critical gap between probabilistic machine learning and absolute cybersecurity guarantees, this dissertation introduces **Project AEGIS-MONAD**. AEGIS-MONAD shifts AI output safety from soft probabilistic filtering to **deterministic formal mathematical proof** embedded directly inside the LLM token decoding pipeline.

---

## 1.2 The AEGIS-MONAD Framework

AEGIS-MONAD establishes a defense-grade, provably secure AI reasoning and infrastructure architecture built upon four core pillars:

1. **Deterministic SMT Monad Logit Transformation:** Integrated directly into the autoregressive sampling loop prior to softmax decoding, a Satisfiability Modulo Theories (SMT) solver evaluates candidate token hypotheses ($v_i$) against formal first-order logic security graphs.
2. **Thread-Isolated Native Concurrency:** To eliminate native C++ memory access violations and race conditions under heavy parallel loads, the framework enforces per-thread `z3.Context()` isolation, ensuring thread-safe evaluation without thread blocking.
3. **Hardware-Attested Confidential Enclaves & Steganographic Provenance:** Execution is secured inside AMD SEV-SNP Virtual Machine Privilege Level 0 (VMPL 0) enclaves. Output vectors undergo (\\epsilon, \\delta)-Differential Privacy perturbation and are tagged with zero-width steganographic markers (`U+200B`/`U+200C`) cryptographically tied to `HW_KEY_0x889_BSU_DAS_2026_EDR`.
4. **Datacenter & Microgrid Telemetry Twin:** A real-time digital twin optimizes compute load against off-grid solar reserves, battery state-of-charge, and direct immersion liquid heat recovery, quantified by the Grid Isolation Index ($GI$).

---

## 1.3 Mathematical Formulation & Core Theorems

### 1.3.1 The Monad SMT Logit Transformation Operator
Let $L_i \\in \\mathbb{R}$ represent the raw candidate logit for token hypothesis $v_i$ generated by the transformer model prior to final probability distribution normalization. The modified logit $\\hat{L}_i$ is defined as:

$$\\hat{L}_i = L_i + \\log \\Phi(v_i)$$

Where $\\Phi(v_i) \\in \\{0, 1\\}$ is an indicator function evaluated over a formal SMT logic constraint graph:

$$\\Phi(v_i) = \\begin{cases} 1 & \\text{if } \\text{SMT\\_Verify}(v_i) = \\text{SAT} \\\\ 0 & \\text{if } \\text{SMT\\_Verify}(v_i) = \\text{UNSAT} \\end{cases}$$

### 1.3.2 Proof of Zero-Violation ($P_{\\text{violation}} = 0$)
When a candidate token $v_i$ violates defined security invariants (e.g., attempting CUI output over an unencrypted channel), the SMT solver returns $\\text{UNSAT}$, setting $\\Phi(v_i) = 0$.

Evaluating the modified logit yields:

$$\\hat{L}_i = L_i + \\log(0) = L_i + (-\\infty) = -\\infty$$

The resulting token probability $P(v_i)$ under Softmax sampling is:

$$P(v_i) = \\frac{e^{\\hat{L}_i}}{\\sum_{j} e^{\\hat{L}_j}} = \\frac{e^{-\\infty}}{\\sum_{j} e^{\\hat{L}_j}} = \\frac{0}{\\sum_{j} e^{\\hat{L}_j}} = 0$$

$$\\therefore P_{\\text{violation}} = 0.0000\\%$$

---

## 1.4 Research Questions & Objectives

* **RQ1:** Can formal SMT solver graphs be embedded into the autoregressive decoding loop of an LLM to guarantee $P_{\\text{violation}} = 0$ while maintaining total latency overhead under 10ms?
* **RQ2:** How can thread-isolated native memory structures prevent memory corruption and race conditions in concurrent multi-threaded C++ SMT contexts during high-throughput inference?
* **RQ3:** To what degree does integrating differential privacy, hardware attestation, and microgrid telemetry twin optimization increase system survivability in forward-deployed tactical command posts?
"""

ch2_content = """# BOWIE STATE UNIVERSITY
## Department of Computer Science — Doctor of Applied Science (D.A.S.) Program

---

### DISSERTATION CHAPTER 2: LITERATURE REVIEW & PRIOR ART

* **Title:** Deterministic Guardrails in Autonomous Large Language Model Pipelines via Thread-Isolated SMT Logit Transformation and Hardware-Attested Memory Enclaves
* **Candidate:** Asaad Morman
* **Degree Program:** Doctor of Applied Science (D.A.S.) in Computer Science
* **Institution:** Bowie State University
* **Hardware Provenance Signature:** `HW_KEY_0x889_BSU_DAS_2026_EDR`

---

## 2.1 Introduction & Theoretical Landscape

The rapid scaling of autoregressive transformer architectures has introduced significant capabilities alongside severe security challenges. As Large Language Models (LLMs) transition from conversational interfaces to autonomous agents operating within defense infrastructure, guaranteeing computational integrity, data privacy, and operational bounds becomes paramount.

Current academic and industry approaches to AI alignment and safety fall into three main paradigms:
1. **Probabilistic Guardrails:** Reinforcement Learning from Human Feedback (RLHF), Direct Preference Optimization (DPO), and system prompt conditioning.
2. **Post-Hoc Runtime Filters:** Secondary screening models, Regex-based output regex parsers, and semantic vector comparison gates.
3. **Hardware & Cryptographic Enclaves:** Trusted Execution Environments (TEEs) and Differential Privacy (\\epsilon, \\delta) mechanisms applied to vector indexes.

---

## 2.2 Probabilistic & Post-Hoc Guardrails: Structural Limits

Standard alignment techniques—such as RLHF and Constitutional AI—attempt to lower the likelihood of harmful token sequences by adjusting model weights during training. However, because output generation relies on Softmax probability distributions, these safety boundaries remain inherently probabilistic.

When candidate logits $L_i$ undergo Softmax transformation:

$$P(v_i) = \\frac{e^{L_i}}{\\sum_{j} e^{L_j}}$$

As long as $L_i > -\\infty$, $P(v_i) > 0$. Under targeted prompt injection, prefix injection, or representation engineering attacks, adversarial inputs systematically shift the logit distribution, allowing restricted or policy-violating tokens to attain non-zero selection probabilities ($P_{\\text{violation}} > 0$).

---

## 2.3 Formal Verification & SMT Logit Constraints

Formal verification using Satisfiability Modulo Theories (SMT) solvers—such as Z3 and CVC5—has long been the gold standard for verifying hardware circuits, cryptographic protocols, and flight control software. SMT solvers evaluate first-order logic formulas over theories including bit-vectors, arrays, and real arithmetic to determine if a formula is Satisfiable ($\\text{SAT}$) or Unsatisfiable ($\\text{UNSAT}$).

AEGIS-MONAD resolves concurrency safety issues via **per-thread `z3.Context()` isolation**, embedding formal SMT checks directly into the autoregressive decoding step before Softmax sampling:

$$\\hat{L}_i = L_i + \\log \\Phi(v_i)$$

Where $\\Phi(v_i) = 0 \\implies \\hat{L}_i = -\\infty \\implies P(v_i) = 0$, achieving mathematical immunity from probabilistic guardrail bypass.
"""

ch1_path = os.path.join(chapter_dir, 'Chapter_01_Introduction.md')
ch2_path = os.path.join(chapter_dir, 'Chapter_02_Literature_Review.md')

with open(ch1_path, 'w', encoding='utf-8') as f:
    f.write(ch1_content)

with open(ch2_path, 'w', encoding='utf-8') as f:
    f.write(ch2_content)

# Copy to notebook_sources
with open(os.path.join(sources_dir, 'Chapter_01_Introduction.md'), 'w', encoding='utf-8') as f:
    f.write(ch1_content)

with open(os.path.join(sources_dir, 'Chapter_02_Literature_Review.md'), 'w', encoding='utf-8') as f:
    f.write(ch2_content)

print(f"[SUCCESS] Wrote Chapter 1 ({os.path.getsize(ch1_path)} bytes) to: {ch1_path}")
print(f"[SUCCESS] Wrote Chapter 2 ({os.path.getsize(ch2_path)} bytes) to: {ch2_path}")
print(f"[SUCCESS] Copied both files to {sources_dir} for NotebookLM import!")
